spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb+srv://gihanvidu123:199884@lerningprojects.qf5lzkz.mongodb.net/?appName=LerningProjects

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
